### PR TITLE
Fixed the (relative) path on the links

### PR DESCRIPTION
**Pull request by corleyma**
The links as written don't work. Fixed the duplicated "feature engineering/" (unnecessary given location of this file/how file paths are globbed), so they work now.

### CODE REVIEW

**Comment by rschindlauer** [comment]
Hi corleyma,
I can't reproduce your issue, the links seem to work fine on https://dato.com/learn/userguide/. Can you describe how you encountered this problem?
Thanks,
Roman

**Comment by corleyma** [comment]
If you start from: https://dato.com/learn/userguide/feature-engineering/numeric_features.html

And look at any of the links on that page, you'll notice they have the form: https://dato.com/learn/userguide/feature-engineering/feature-engineering/<feature_name>.html

The duplicated **/feature-engineering/** points to a dir that doesn't exist. 

*E.g.,* the link to Quadratic Features is: https://dato.com/learn/userguide/feature-engineering/feature-engineering/quadratic_features.html

Simply removing the 'feature-engineering/' prefix from the links works, again because of how partial paths are inferred.

**Comment by corleyma** [comment]
Note, I'm not talking about the links from the sidebar, but the actual links specified in the markdown on **numeric_features.html**.

**Comment by rschindlauer** [comment]
Got it--I didn't look closely enough and thought you were referring to the TOC. Good catch, thanks for taking the time to fix!

**Comment by corleyma** [comment]
No problem!  I found Graphlab through the Coursera course, got curious about the open source components.  Kudos and gratitude for the awesome project.

**Pull request merged**
