### PR TITLE
Added Heads to each page

### PR DESCRIPTION
**Pull request by markeno**
Added a H1 type title to each page so the user is assured they are on
the page they clicked on.

### CODE REVIEW

**Comment by markeno** [comment]
Hey @chrisdubois I added a page title to each page so that the user has a clear confirmation that they got the page they clicked on in the left sidebar. Please proof to make sure I added the right copy... most of them I just copied the link name, but some I added a bit more copy so it read better... feel free to assign any changes back to me. Thanks!

cc: @timmuss @znation

**Comment by znation** [comment]
@chrisdubois @timmuss Should we merge this?

**Comment by chrisdubois** [comment]
Is there an example build or a screenshot?

**Comment by znation** [comment]
@chrisdubois No, but you can pull down the change and build it locally if you want to see how it looks. It's worth noting that [GitBook's own GitBook](https://github.com/GitbookIO/documentation) does put H1 elements at the top of each chapter.

**Comment by znation** [comment]
Here are a couple screenshots, with and without the GitBook header (which you have to scroll up to see):

screen shot 2015-07-08 at 8 43 35 pm
screen shot 2015-07-08 at 8 43 28 pm

**Comment by chrisdubois** [comment]
Sorry to be dense, but what's the difference?

**Comment by znation** [comment]
Here are the before screenshots:
screen shot 2015-07-08 at 9 25 34 pm
screen shot 2015-07-08 at 9 25 25 pm

**Comment by chrisdubois** [comment]
Ah, got it. LGTM. Any objections?

**Pull request merged**
